title: Lotrives
description: "Una mirada al mundo que somos"
theme: minima

# Menú simple (no pongas index.md aquí)
header_pages:
  - acerca.md
  - archivo.md
  - newsletter.md
  - temas.md

# Opcionales recomendados (compatibles con GitHub Pages)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Extras cómodos
show_excerpts: true        # la home muestra el excerpt del post si lo hay
timezone: Europe/Madrid
