title: "Lotrives"
description: "Lotrives · Una mirada al mundo que somos"
author:
  name: "© José Manuel Grau Navarro"
lang: "es"
timezone: Europe/Madrid

# Tema Minima 3 en commit estable
remote_theme: jekyll/minima@d4d779a

url: "https://lotrives.github.io"
baseurl: ""

permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

minima:
  nav_pages:
    - acerca.md
    - archivo.md
    - buscar.md
    - etiquetas.md
    - newsletter.md
  show_excerpts: true
  skin: auto
  social_links:
    - title: "X"
      icon: x-twitter
      url: "https://twitter.com/jmgraunavarro"
    - title: "GitHub"
      icon: github
      url: "https://github.com/lotrives"
  hide_site_feed_link: true  # oculta el enlace “Subscribe via RSS” del footer

twitter_username: jmgraunavarro
github_username: lotrives

sass:
  style: compressed
