title: Lotrives
description: "Una mirada al mundo que somos"
theme: minima

author: "Jos√© Manuel Grau Navarro"

header_pages:
  - acerca.md
  - archivo.md
  - newsletter.md
  - etiquetas.md
  - buscar.md


plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

show_excerpts: true
timezone: Europe/Madrid
