title: "Lotrives"
description: "Lotrives · Una mirada al mundo que somos"
author:
  name: "© José Manuel Grau Navarro"
lang: "es"
timezone: "Europe/Madrid"

# Minima 3 moderno (commit estable con mejoras en nav móvil)
remote_theme: "jekyll/minima@5f61d94"

url: "https://lotrives.github.io"
baseurl: ""

permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

minima:
  nav_pages:
    - acerca.md
    - archivo.md
    - buscar.md
    - etiquetas.md
    - newsletter.md
  show_excerpts: true
  hide_site_feed_link: true
  # skin auto (claro/oscuro)
  skin: auto

twitter_username: "jmgraunavarro"
github_username: "lotrives"

sass:
  style: compressed
