title: Lotrives
description: "Una mirada al mundo que somos"
theme: minima

author: "JosÃ© Manuel Grau Navarro"

# ðŸ‘‡ Clave para que {{ page.url | absolute_url }} funcione bien
url: https://lotrives.github.io
baseurl: ""  # no pongas nada aquÃ­ (solo comillas)

header_pages:
  - acerca.md
  - archivo.md
  - newsletter.md
  - etiquetas.md
  - buscar.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

show_excerpts: true
timezone: Europe/Madrid
