title: "Lotrives"
author: "José Manuel Grau Navarro"
description: "Una mirada al mundo que somos"

theme: minima

# Opcional: configuración de enlaces y posts
markdown: kramdown
plugins:
  - jekyll-feed

# Datos del sitio
url: "https://lotrives.github.io"
baseurl: ""

# Opcional: idioma y formato de fecha
lang: "es"
show_excerpts: true
